fn main() {
    println!("================================================");
    println!("  RUSTDSA - Data Structures & Algorithms in Rust");
    println!("================================================");
    println!();
    println!("Run individual examples with:");
    println!("  cargo run --example <name>");
    println!();
    println!("Available examples:");
    println!();
    println!("  Core Concepts:");
    println!("    variables_mutability_example");
    println!("    data_types_type_inference_example");
    println!("    ownership_borrowing_example");
    println!("    slices_references_example");
    println!("    structs_enums_example");
    println!("    pattern_matching_example");
    println!("    functions_modules_example");
    println!("    generics_traits_example");
    println!("    error_handling_example");
    println!("    iterators_closures_example");
    println!();
    println!("  Data Structures:");
    println!("    arrays_example");
    println!("    vectors_example");
    println!("    strings_example");
    println!("    linked_list_example");
    println!("    stack_example");
    println!("    queue_example");
    println!("    hash_map_example");
    println!("    sets_example");
    println!("    trees_example");
    println!("    binary_search_tree_example");
    println!("    heap_example");
    println!("    graphs_example");
    println!();
    println!("  Algorithms:");
    println!("    recursion_example");
    println!("    bubble_sort_example");
    println!("    selection_sort_example");
    println!("    insertion_sort_example");
    println!("    merge_sort_example");
    println!("    quick_sort_example");
    println!("    heap_sort_example");
    println!("    counting_sort_example");
    println!("    linear_search_example");
    println!("    binary_search_example");
    println!("    exponential_search_example");
    println!("    interpolation_search_example");
    println!("    dynamic_programming_example");
    println!("    greedy_algorithm_example");
    println!("    backtracking_example");
    println!("    bit_manipulation_example");
    println!();
    println!("  Complexity:");
    println!("    time_complexity_example");
    println!("    space_complexity_example");
    println!();
    println!("Example: cargo run --example arrays_example");
}
